### ISSUE TITLE
Mark front() const

### ISSUE THREAD

**Issue by xeruf** [rigtorp/SPSCQueue#19]
Is there a reason why front() is not marked const?

**Comment by rigtorp** [comment]
The declaration is `T *front() noexcept;`. Since `T*` is not const `front()` cannot be const. `T*` is not const since a consumer might want to move from T* or there might be some scratch buffer for the consumer in the T*. Since a consumer needs to call `pop()` a consumer needs mutable access to the queue object anyway. 

That said, it's possible to add a second `front()` implementation that returns a `const T*` and is marked as const.
