### ISSUE TITLE
mmap IPC allocator example

### ISSUE THREAD

**Issue by PengyiPan** [rigtorp/SPSCQueue#33]
Hi there,

I'm trying to use your awesome queue to do inter-process shared memory communication on linux. 

I think it can be done with some modification to the huge page allocator example, but coundn't come up with a correct implementation. 

If IPC is possible, could you please add an IPC demo to the example? Many thanks.

**Comment by rigtorp** [comment]
Yes you need to placement new the `SPSCQueue` in mmaped shared memory and supply a allocator that allocates the buffer inside the same shared memory.

**Comment by Green-Sky** [comment]
SPSCQueue can not be placed into shared memory as is because, `T *slots_;` and `Allocator allocator_;` assume the same pointers, which is not true across process boundaries.

Also, the atomics need to be lock less https://en.cppreference.com/w/cpp/atomic/atomic/is_lock_free

I am also looking into doing ipc using a lockfree queue and shared memory. :)
